from pydantic import BaseModel
from typing import List, Dict

class MusicData(BaseModel):
    languages: List[str] = [
        "Hindi", "English", "Punjabi", "Tamil", "Telugu", "Marathi", "Bengali", "Gujarati", "Kannada", "Malayalam",
        "Spanish", "French", "Korean", "Japanese", "Arabic", "Portuguese", "Russian", "Italian", "German", "Chinese"
    ]

    artists: Dict[str, List[Dict]] = {
        "Hindi": [
            {"name": "Arijit Singh", "photo": "/models/images/ArijitSingh.jpg"},
            {"name": "Shreya Ghoshal", "photo": "/models/images/ShreyaGhoshal.jpg"},
            {"name": "Diljit Dosanjh", "photo": "/models/images/DiljitDosanjh.jpg"},
            {"name": "Badshah", "photo": "/models/images/Badshah.jpg"},
            {"name": "AP Dhillon", "photo": "/models/images/APDhillon.jpg"},
            {"name": "Darshan Raval", "photo": "/models/images/DarshanRaval.jpg"},
            {"name": "Karan Aujla", "photo": "/models/images/KaranAujla.jpg"},
            {"name": "Shubh", "photo": "/models/images/Shubh.jpg"},
            {"name": "Jubin Nautiyal", "photo": "/models/images/JubinNautiyal.jpg"},
            {"name": "Neha Kakkar", "photo": "/models/images/NehaKakkar.jpg"},
            {"name": "Guru Randhawa", "photo": "/models/images/GuruRandhawa.jpg"},
            {"name": "King", "photo": "/models/images/King.jpg"},
            {"name": "Seedhe Maut", "photo": "/models/images/SeedheMaut.jpg"},
            {"name": "Talwiinder", "photo": "/models/images/Talwiinder.jpg"},
            {"name": "Lata Mangeshkar", "photo": "/models/images/LataMangeshkar.jpg"},
            {"name": "Mohammed Rafi", "photo": "/models/images/MohammedRafi.jpg"},
            {"name": "Kishore Kumar", "photo": "/models/images/KishoreKumar.jpg"},
            {"name": "Mukesh", "photo": "/models/images/Mukesh.jpg"},
            {"name": "Ashok Kumar", "photo": "/models/images/AshokKumar.jpg"},
            {"name": "Hemant Kumar", "photo": "/models/images/HemantKumar.jpg"}
        ],
        "English": [
            {"name": "Taylor Swift", "photo": "/models/images/TaylorSwift.jpg"},
            {"name": "The Weeknd", "photo": "/models/images/TheWeeknd.jpg"},
            {"name": "Billie Eilish", "photo": "/models/images/BillieEilish.jpg"},
            {"name": "Ed Sheeran", "photo": "/models/images/EdSheeran.jpg"},
            {"name": "Drake", "photo": "/models/images/Drake.jpg"},
            {"name": "Ariana Grande", "photo": "/models/images/ArianaGrande.jpg"},
            {"name": "Post Malone", "photo": "/models/images/PostMalone.jpg"},
            {"name": "Harry Styles", "photo": "/models/images/HarryStyles.jpg"},
            {"name": "Olivia Rodrigo", "photo": "/models/images/OliviaRodrigo.jpg"},
            {"name": "Dua Lipa", "photo": "/models/images/DuaLipa.jpg"},
            {"name": "Doja Cat", "photo": "/models/images/DojaCat.jpg"},
            {"name": "Travis Scott", "photo": "/models/images/TravisScott.jpg"},
            {"name": "SZA", "photo": "/models/images/SZA.jpg"},
            {"name": "Kendrick Lamar", "photo": "/models/images/KendrickLamar.jpg"},
            {"name": "Michael Jackson", "photo": "/models/images/MichaelJackson.jpg"},
            {"name": "Elvis Presley", "photo": "/models/images/ElvisPresley.jpg"},
            {"name": "Freddie Mercury", "photo": "/models/images/FreddieMercury.jpg"},
            {"name": "Aretha Franklin", "photo": "/models/images/ArethaFranklin.jpg"},
            {"name": "Bob Dylan", "photo": "/models/images/BobDylan.jpg"},
            {"name": "Whitney Houston", "photo": "/models/images/WhitneyHouston.jpg"}
        ],
        "Punjabi": [
            {"name": "Sidhu Moose Wala", "photo": "/models/images/SidhuMooseWala.jpg"},
            {"name": "Diljit Dosanjh", "photo": "/models/images/DiljitDosanjh.jpg"},
            {"name": "AP Dhillon", "photo": "/models/images/APDhillon.jpg"},
            {"name": "Karan Aujla", "photo": "/models/images/KaranAujla.jpg"},
            {"name": "Shubh", "photo": "/models/images/Shubh.jpg"},
            {"name": "Guru Randhawa", "photo": "/models/images/GuruRandhawa.jpg"},
            {"name": "Parmish Verma", "photo": "/models/images/ParmishVerma.jpg"},
            {"name": "Mankirt Aulakh", "photo": "/models/images/MankirtAulakh.jpg"},
            {"name": "Jass Manak", "photo": "/models/images/JassManak.jpg"},
            {"name": "Garry Sandhu", "photo": "/models/images/GarrySandhu.jpg"},
            {"name": "Byg Byrd", "photo": "/models/images/BygByrd.jpg"},
            {"name": "Tarsem Jassar", "photo": "/models/images/TarsemJassar.jpg"},
            {"name": "R Nait", "photo": "/models/images/RNait.jpg"},
            {"name": "Sunny Malton", "photo": "/models/images/SunnyMalton.jpg"},
            {"name": "Kuldeep Manak", "photo": "/models/images/KuldeepManak.jpg"},
            {"name": "Gurdas Maan", "photo": "/models/images/GurdasMaan.jpg"},
            {"name": "Amar Singh Chamkila", "photo": "/models/images/AmarSinghChamkila.jpg"},
            {"name": "Surinder Shinda", "photo": "/models/images/SurinderShinda.jpg"},
            {"name": "K. Deep", "photo": "/models/images/KDeep.jpg"},
            {"name": "Babbu Maan", "photo": "/models/images/BabbuMaan.jpg"}
        ],
        "Tamil": [
            {"name": "Anirudh Ravichander", "photo": "/models/images/AnirudhRavichander.jpg"},
            {"name": "Sid Sriram", "photo": "/models/images/SidSriram.jpg"},
            {"name": "Yuvan Shankar Raja", "photo": "/models/images/YuvanShankarRaja.jpg"},
            {"name": "Hiphop Tamizha", "photo": "/models/images/HiphopTamizha.jpg"},
            {"name": "Santhosh Narayanan", "photo": "/models/images/SanthoshNarayanan.jpg"},
            {"name": "G. V. Prakash Kumar", "photo": "/models/images/GVPrakashKumar.jpg"},
            {"name": "D. Imman", "photo": "/models/images/DImman.jpg"},
            {"name": "Vijay Antony", "photo": "/models/images/VijayAntony.jpg"},
            {"name": "A. R. Rahman", "photo": "/models/images/AR Rahman.jpg"},
            {"name": "Harris Jayaraj", "photo": "/models/images/HarrisJayaraj.jpg"},
            {"name": "Thaman S", "photo": "/models/images/ThamanS.jpg"},
            {"name": "Deva", "photo": "/models/images/Deva.jpg"},
            {"name": "Ilaiyaraaja", "photo": "/models/images/Ilaiyaraaja.jpg"},
            {"name": "Karthik", "photo": "/models/images/Karthik.jpg"},
            {"name": "M. S. Viswanathan", "photo": "/models/images/MSViswanathan.jpg"},
            {"name": "K. V. Mahadevan", "photo": "/models/images/KVMahadevan.jpg"},
            {"name": "T. M. Soundararajan", "photo": "/models/images/TMSoundararajan.jpg"},
            {"name": "P. Susheela", "photo": "/models/images/PSusheela.jpg"},
            {"name": "S. Janaki", "photo": "/models/images/SJanaki.jpg"},
            {"name": "S. P. Balasubrahmanyam", "photo": "/models/images/SPBalasubrahmanyam.jpg"}
        ],
        "Telugu": [
            {"name": "DSP", "photo": "/models/images/DSP.jpg"},
            {"name": "Thaman S", "photo": "/models/images/ThamanS.jpg"},
            {"name": "Mickey J Meyer", "photo": "/models/images/MickeyJMeyer.jpg"},
            {"name": "Devi Sri Prasad", "photo": "/models/images/DeviSriPrasad.jpg"},
            {"name": "Anup Rubens", "photo": "/models/images/AnupRubens.jpg"},
            {"name": "Gopi Sunder", "photo": "/models/images/GopiSunder.jpg"},
            {"name": "Chaitan Bharadwaj", "photo": "/models/images/ChaitanBharadwaj.jpg"},
            {"name": "S. Thaman", "photo": "/models/images/SThaman.jpg"},
            {"name": "Mani Sharma", "photo": "/models/images/ManiSharma.jpg"},
            {"name": "Harris Jayaraj", "photo": "/models/images/HarrisJayaraj.jpg"},
            {"name": "A. R. Rahman", "photo": "/models/images/AR Rahman.jpg"},
            {"name": "Karthik", "photo": "/models/images/Karthik.jpg"},
            {"name": "Sid Sriram", "photo": "/models/images/SidSriram.jpg"},
            {"name": "Anurag Kulkarni", "photo": "/models/images/AnuragKulkarni.jpg"},
            {"name": "Ghantasala", "photo": "/models/images/Ghantasala.jpg"},
            {"name": "S. P. Balasubrahmanyam", "photo": "/models/images/SPBalasubrahmanyam.jpg"},
            {"name": "P. Susheela", "photo": "/models/images/PSusheela.jpg"},
            {"name": "M. S. Viswanathan", "photo": "/models/images/MSViswanathan.jpg"},
            {"name": "K. V. Mahadevan", "photo": "/models/images/KVMahadevan.jpg"},
            {"name": "S. Janaki", "photo": "/models/images/SJanaki.jpg"}
        ],
        "Marathi": [
            {"name": "Ajay-Atul", "photo": "/models/images/AjayAtul.jpg"},
            {"name": "Shreya Ghoshal", "photo": "/models/images/ShreyaGhoshal.jpg"},
            {"name": "Sandeep Khare", "photo": "/models/images/SandeepKhare.jpg"},
            {"name": "Swapnil Bandodkar", "photo": "/models/images/SwapnilBandodkar.jpg"},
            {"name": "Sachin Pilgaonkar", "photo": "/models/images/SachinPilgaonkar.jpg"},
            {"name": "Amitraj", "photo": "/models/images/Amitraj.jpg"},
            {"name": "Hrishikesh Ranade", "photo": "/models/images/HrishikeshRanade.jpg"},
            {"name": "Sandeep Khare", "photo": "/models/images/SandeepKhare.jpg"},
            {"name": "Vishal Dadlani", "photo": "/models/images/VishalDadlani.jpg"},
            {"name": "Siddharth Mahadevan", "photo": "/models/images/SiddharthMahadevan.jpg"},
            {"name": "Adarsh Shinde", "photo": "/models/images/AdarshShinde.jpg"},
            {"name": "Aarya Ambekar", "photo": "/models/images/AaryaAmbekar.jpg"},
            {"name": "Sanjay Jadhav", "photo": "/models/images/SanjayJadhav.jpg"},
            {"name": "Mangesh Borgaonkar", "photo": "/models/images/MangeshBorgaonkar.jpg"},
            {"name": "Lata Mangeshkar", "photo": "/models/images/LataMangeshkar.jpg"},
            {"name": "Kishore Kumar", "photo": "/models/images/KishoreKumar.jpg"},
            {"name": "Mukesh", "photo": "/models/images/Mukesh.jpg"},
            {"name": "Ashok Kumar", "photo": "/models/images/AshokKumar.jpg"},
            {"name": "Hemant Kumar", "photo": "/models/images/HemantKumar.jpg"},
            {"name": "Sudhir Phadke", "photo": "/models/images/SudhirPhadke.jpg"}
        ],
        "Bengali": [
            {"name": "Arijit Singh", "photo": "/models/images/ArijitSingh.jpg"},
            {"name": "Shreya Ghoshal", "photo": "/models/images/ShreyaGhoshal.jpg"},
            {"name": "Anupam Roy", "photo": "/models/images/AnupamRoy.jpg"},
            {"name": "Lagnajita Chakraborty", "photo": "/models/images/LagnajitaChakraborty.jpg"},
            {"name": "Rupam Islam", "photo": "/models/images/RupamIslam.jpg"},
            {"name": "Anjan Dutt", "photo": "/models/images/AnjanDutt.jpg"},
            {"name": "Nachiketa", "photo": "/models/images/Nachiketa.jpg"},
            {"name": "Kishore Kumar", "photo": "/models/images/KishoreKumar.jpg"},
            {"name": "Srikanto Acharya", "photo": "/models/images/SrikantoAcharya.jpg"},
            {"name": "Srabani Sen", "photo": "/models/images/SrabaniSen.jpg"},
            {"name": "Srikanto Acharya", "photo": "/models/images/SrikantoAcharya.jpg"},
            {"name": "Rabindra Sangeet", "photo": "/models/images/RabindraSangeet.jpg"},
            {"name": "Kabir Suman", "photo": "/models/images/KabirSuman.jpg"},
            {"name": "Suman Chattopadhyay", "photo": "/models/images/SumanChattopadhyay.jpg"},
            {"name": "Rabindranath Tagore", "photo": "/models/images/RabindranathTagore.jpg"},
            {"name": "Kazi Nazrul Islam", "photo": "/models/images/KaziNazrulIslam.jpg"},
            {"name": "Hemanta Mukherjee", "photo": "/models/images/HemantaMukherjee.jpg"},
            {"name": "Sandhya Mukherjee", "photo": "/models/images/SandhyaMukherjee.jpg"},
            {"name": "Manna Dey", "photo": "/models/images/MannaDey.jpg"},
            {"name": "Suchitra Mitra", "photo": "/models/images/SuchitraMitra.jpg"}
        ],
        "Gujarati": [
            {"name": "Darshan Raval", "photo": "/models/images/DarshanRaval.jpg"},
            {"name": "Jigardan Gadhavi", "photo": "/models/images/JigardanGadhavi.jpg"},
            {"name": "Aishwarya Majmudar", "photo": "/models/images/AishwaryaMajmudar.jpg"},
            {"name": "Kinjal Dave", "photo": "/models/images/KinjalDave.jpg"},
            {"name": "Geeta Rabari", "photo": "/models/images/GeetaRabari.jpg"},
            {"name": "Mihir Prajapati", "photo": "/models/images/MihirPrajapati.jpg"},
            {"name": "Siddharth Amit Bhavsar", "photo": "/models/images/SiddharthAmitBhavsar.jpg"},
            {"name": "Vishal Dadlani", "photo": "/models/images/VishalDadlani.jpg"},
            {"name": "Aarya Ambekar", "photo": "/models/images/AaryaAmbekar.jpg"},
            {"name": "Sanjay Jadhav", "photo": "/models/images/SanjayJadhav.jpg"},
            {"name": "Mangesh Borgaonkar", "photo": "/models/images/MangeshBorgaonkar.jpg"},
            {"name": "Adarsh Shinde", "photo": "/models/images/AdarshShinde.jpg"},
            {"name": "Sandeep Khare", "photo": "/models/images/SandeepKhare.jpg"},
            {"name": "Swapnil Bandodkar", "photo": "/models/images/SwapnilBandodkar.jpg"},
            {"name": "Lata Mangeshkar", "photo": "/models/images/LataMangeshkar.jpg"},
            {"name": "Kishore Kumar", "photo": "/models/images/KishoreKumar.jpg"},
            {"name": "Mukesh", "photo": "/models/images/Mukesh.jpg"},
            {"name": "Ashok Kumar", "photo": "/models/images/AshokKumar.jpg"},
            {"name": "Hemant Kumar", "photo": "/models/images/HemantKumar.jpg"},
            {"name": "Sudhir Phadke", "photo": "/models/images/SudhirPhadke.jpg"}
        ],
        "Kannada": [
            {"name": "S. P. Balasubrahmanyam", "photo": "/models/images/SPBalasubrahmanyam.jpg"},
            {"name": "Rajesh Krishnan", "photo": "/models/images/RajeshKrishnan.jpg"},
            {"name": "K. S. Chithra", "photo": "/models/images/KSChithra.jpg"},
            {"name": "V. Harikrishna", "photo": "/models/images/VHarikrishna.jpg"},
            {"name": "Anand Audio", "photo": "/models/images/AnandAudio.jpg"},
            {"name": "Arjun Janya", "photo": "/models/images/ArjunJanya.jpg"},
            {"name": "Mano Murthy", "photo": "/models/images/ManoMurthy.jpg"},
            {"name": "Hamsalekha", "photo": "/models/images/Hamsalekha.jpg"},
            {"name": "Ravi Basrur", "photo": "/models/images/RaviBasrur.jpg"},
            {"name": "B. Ajaneesh Loknath", "photo": "/models/images/BAjaneeshLoknath.jpg"},
            {"name": "S. P. Balasubrahmanyam", "photo": "/models/images/SPBalasubrahmanyam.jpg"},
            {"name": "K. S. Chithra", "photo": "/models/images/KSChithra.jpg"},
            {"name": "Rajesh Krishnan", "photo": "/models/images/RajeshKrishnan.jpg"},
            {"name": "V. Harikrishna", "photo": "/models/images/VHarikrishna.jpg"},
            {"name": "P. B. Sreenivas", "photo": "/models/images/PBSreenivas.jpg"},
            {"name": "P. Susheela", "photo": "/models/images/PSusheela.jpg"},
            {"name": "S. Janaki", "photo": "/models/images/SJanaki.jpg"},
            {"name": "K. S. Chithra", "photo": "/models/images/KSChithra.jpg"},
            {"name": "S. P. Balasubrahmanyam", "photo": "/models/images/SPBalasubrahmanyam.jpg"},
            {"name": "Rajkumar", "photo": "/models/images/Rajkumar.jpg"}
        ],
        "Malayalam": [
            {"name": "Shreya Ghoshal", "photo": "/models/images/ShreyaGhoshal.jpg"},
            {"name": "Sithara Krishnakumar", "photo": "/models/images/SitharaKrishnakumar.jpg"},
            {"name": "Gopi Sunder", "photo": "/models/images/GopiSunder.jpg"},
            {"name": "M. G. Sreekumar", "photo": "/models/images/MGSreekumar.jpg"},
            {"name": "K. J. Yesudas", "photo": "/models/images/KJYesudas.jpg"},
            {"name": "P. Jayachandran", "photo": "/models/images/PJayachandran.jpg"},
            {"name": "Sujatha Mohan", "photo": "/models/images/SujathaMohan.jpg"},
            {"name": "S. Janaki", "photo": "/models/images/SJanaki.jpg"},
            {"name": "M. G. Sreekumar", "photo": "/models/images/MGSreekumar.jpg"},
            {"name": "K. S. Chithra", "photo": "/models/images/KSChithra.jpg"},
            {"name": "Sithara Krishnakumar", "photo": "/models/images/SitharaKrishnakumar.jpg"},
            {"name": "Shreya Ghoshal", "photo": "/models/images/ShreyaGhoshal.jpg"},
            {"name": "Gopi Sunder", "photo": "/models/images/GopiSunder.jpg"},
            {"name": "M. G. Sreekumar", "photo": "/models/images/MGSreekumar.jpg"},
            {"name": "K. J. Yesudas", "photo": "/models/images/KJYesudas.jpg"},
            {"name": "P. Susheela", "photo": "/models/images/PSusheela.jpg"},
            {"name": "S. Janaki", "photo": "/models/images/SJanaki.jpg"},
            {"name": "M. G. Sreekumar", "photo": "/models/images/MGSreekumar.jpg"},
            {"name": "K. S. Chithra", "photo": "/models/images/KSChithra.jpg"},
            {"name": "P. Jayachandran", "photo": "/models/images/PJayachandran.jpg"}
        ],
        "Spanish": [
            {"name": "Bad Bunny", "photo": "/models/images/BadBunny.jpg"},
            {"name": "Shakira", "photo": "/models/images/Shakira.jpg"},
            {"name": "J Balvin", "photo": "/models/images/JBalvin.jpg"},
            {"name": "Maluma", "photo": "/models/images/Maluma.jpg"},
            {"name": "Rosalía", "photo": "/models/images/Rosalia.jpg"},
            {"name": "Anitta", "photo": "/models/images/Anitta.jpg"},
            {"name": "Karol G", "photo": "/models/images/KarolG.jpg"},
            {"name": "Ozuna", "photo": "/models/images/Ozuna.jpg"},
            {"name": "Daddy Yankee", "photo": "/models/images/DaddyYankee.jpg"},
            {"name": "Luis Fonsi", "photo": "/models/images/LuisFonsi.jpg"},
            {"name": "Enrique Iglesias", "photo": "/models/images/EnriqueIglesias.jpg"},
            {"name": "Ricky Martin", "photo": "/models/images/RickyMartin.jpg"},
            {"name": "Romeo Santos", "photo": "/models/images/RomeoSantos.jpg"},
            {"name": "Marc Anthony", "photo": "/models/images/MarcAnthony.jpg"},
            {"name": "Celia Cruz", "photo": "/models/images/CeliaCruz.jpg"},
            {"name": "Gloria Estefan", "photo": "/models/images/GloriaEstefan.jpg"},
            {"name": "Julio Iglesias", "photo": "/models/images/JulioIglesias.jpg"},
            {"name": "Vicente Fernández", "photo": "/models/images/VicenteFernandez.jpg"},
            {"name": "Juan Gabriel", "photo": "/models/images/JuanGabriel.jpg"},
            {"name": "José José", "photo": "/models/images/JoseJose.jpg"}
        ],
        "French": [
            {"name": "Indila", "photo": "/models/images/Indila.jpg"},
            {"name": "Stromae", "photo": "/models/images/Stromae.jpg"},
            {"name": "Ed Sheeran", "photo": "/models/images/EdSheeran.jpg"},
            {"name": "Christine and the Queens", "photo": "/models/images/ChristineAndTheQueens.jpg"},
            {"name": "Zaz", "photo": "/models/images/Zaz.jpg"},
            {"name": "Mylène Farmer", "photo": "/models/images/MyleneFarmer.jpg"},
            {"name": "Vianney", "photo": "/models/images/Vianney.jpg"},
            {"name": "Louane", "photo": "/models/images/Louane.jpg"},
            {"name": "Angèle", "photo": "/models/images/Angele.jpg"},
            {"name": "Damso", "photo": "/models/images/Damso.jpg"},
            {"name": "Ninho", "photo": "/models/images/Ninho.jpg"},
            {"name": "Nekfeu", "photo": "/models/images/Nekfeu.jpg"},
            {"name": "Orelsan", "photo": "/models/images/Orelsan.jpg"},
            {"name": "Jul", "photo": "/models/images/Jul.jpg"},
            {"name": "Edith Piaf", "photo": "/models/images/EdithPiaf.jpg"},
            {"name": "Charles Aznavour", "photo": "/models/images/CharlesAznavour.jpg"},
            {"name": "Jacques Brel", "photo": "/models/images/JacquesBrel.jpg"},
            {"name": "Serge Gainsbourg", "photo": "/models/images/SergeGainsbourg.jpg"},
            {"name": "Johnny Hallyday", "photo": "/models/images/JohnnyHallyday.jpg"},
            {"name": "Dalida", "photo": "/models/images/Dalida.jpg"}
        ],
        "Korean": [
            {"name": "BTS", "photo": "/models/images/BTS.jpg"},
            {"name": "BLACKPINK", "photo": "/models/images/BLACKPINK.jpg"},
            {"name": "TWICE", "photo": "/models/images/TWICE.jpg"},
            {"name": "EXO", "photo": "/models/images/EXO.jpg"},
            {"name": "IU", "photo": "/models/images/IU.jpg"},
            {"name": "Stray Kids", "photo": "/models/images/StrayKids.jpg"},
            {"name": "ATEEZ", "photo": "/models/images/ATEEZ.jpg"},
            {"name": "SEVENTEEN", "photo": "/models/images/SEVENTEEN.jpg"},
            {"name": "Red Velvet", "photo": "/models/images/RedVelvet.jpg"},
            {"name": "NCT", "photo": "/models/images/NCT.jpg"},
            {"name": "TXT", "photo": "/models/images/TXT.jpg"},
            {"name": "ITZY", "photo": "/models/images/ITZY.jpg"},
            {"name": "IVE", "photo": "/models/images/IVE.jpg"},
            {"name": "NewJeans", "photo": "/models/images/NewJeans.jpg"},
            {"name": "BoA", "photo": "/models/images/BoA.jpg"},
            {"name": "Rain", "photo": "/models/images/Rain.jpg"},
            {"name": "TVXQ", "photo": "/models/images/TVXQ.jpg"},
            {"name": "Super Junior", "photo": "/models/images/SuperJunior.jpg"},
            {"name": "Girls' Generation", "photo": "/models/images/GirlsGeneration.jpg"},
            {"name": "Wonder Girls", "photo": "/models/images/WonderGirls.jpg"}
        ],
        "Japanese": [
            {"name": "YOASOBI", "photo": "/models/images/YOASOBI.jpg"},
            {"name": "Ado", "photo": "/models/images/Ado.jpg"},
            {"name": "LiSA", "photo": "/models/images/LiSA.jpg"},
            {"name": "Official Hige Dandism", "photo": "/models/images/OfficialHigeDandism.jpg"},
            {"name": "Aimer", "photo": "/models/images/Aimer.jpg"},
            {"name": "Kenshi Yonezu", "photo": "/models/images/KenshiYonezu.jpg"},
            {"name": "Vaundy", "photo": "/models/images/Vaundy.jpg"},
            {"name": "Zutto Mayonaka de Iinoni", "photo": "/models/images/ZuttoMayonakaDeIinoni.jpg"},
            {"name": "King Gnu", "photo": "/models/images/KingGnu.jpg"},
            {"name": "Bump of Chicken", "photo": "/models/images/BumpOfChicken.jpg"},
            {"name": "Radwimps", "photo": "/models/images/Radwimps.jpg"},
            {"name": "One OK Rock", "photo": "/models/images/OneOKRock.jpg"},
            {"name": "Babymetal", "photo": "/models/images/Babymetal.jpg"},
            {"name": "AKB48", "photo": "/models/images/AKB48.jpg"},
            {"name": "Utada Hikaru", "photo": "/models/images/UtadaHikaru.jpg"},
            {"name": "Ayumi Hamasaki", "photo": "/models/images/AyumiHamasaki.jpg"},
            {"name": "Namie Amuro", "photo": "/models/images/NamieAmuro.jpg"},
            {"name": "Mr. Children", "photo": "/models/images/MrChildren.jpg"},
            {"name": "B'z", "photo": "/models/images/Bz.jpg"},
            {"name": "X Japan", "photo": "/models/images/XJapan.jpg"}
        ],
        "Arabic": [
            {"name": "Mohamed Ramadan", "photo": "/models/images/MohamedRamadan.jpg"},
            {"name": "Amr Diab", "photo": "/models/images/AmrDiab.jpg"},
            {"name": "Nancy Ajram", "photo": "/models/images/NancyAjram.jpg"},
            {"name": "Tamer Hosny", "photo": "/models/images/TamerHosny.jpg"},
            {"name": "Hussain Al Jassmi", "photo": "/models/images/HussainAlJassmi.jpg"},
            {"name": "Myriam Fares", "photo": "/models/images/MyriamFares.jpg"},
            {"name": "Elissa", "photo": "/models/images/Elissa.jpg"},
            {"name": "Wael Kfoury", "photo": "/models/images/WaelKfoury.jpg"},
            {"name": "Rami Sabry", "photo": "/models/images/RamiSabry.jpg"},
            {"name": "Saber Rebai", "photo": "/models/images/SaberRebai.jpg"},
            {"name": "Kazem Al Saher", "photo": "/models/images/KazemAlSaher.jpg"},
            {"name": "Fairuz", "photo": "/models/images/Fairuz.jpg"},
            {"name": "Majida El Roumi", "photo": "/models/images/MajidaElRoumi.jpg"},
            {"name": "Assi El Helani", "photo": "/models/images/AssiElHelani.jpg"},
            {"name": "Umm Kulthum", "photo": "/models/images/UmmKulthum.jpg"},
            {"name": "Abdel Halim Hafez", "photo": "/models/images/AbdelHalimHafez.jpg"},
            {"name": "Farid Al-Atrash", "photo": "/models/images/FaridAlAtrash.jpg"},
            {"name": "Mohammed Abdel Wahab", "photo": "/models/images/MohammedAbdelWahab.jpg"},
            {"name": "Warda Al-Jazairia", "photo": "/models/images/WardaAlJazairia.jpg"},
            {"name": "Sabah", "photo": "/models/images/Sabah.jpg"}
        ],
        "Portuguese": [
            {"name": "Anitta", "photo": "/models/images/Anitta.jpg"},
            {"name": "Gustavo Lima", "photo": "/models/images/GustavoLima.jpg"},
            {"name": "Marília Mendonça", "photo": "/models/images/MariliaMendonca.jpg"},
            {"name": "Jorge & Mateus", "photo": "/models/images/JorgeAndMateus.jpg"},
            {"name": "Luísa Sonza", "photo": "/models/images/LuisaSonza.jpg"},
            {"name": "Ludmilla", "photo": "/models/images/Ludmilla.jpg"},
            {"name": "Iza", "photo": "/models/images/Iza.jpg"},
            {"name": "Gloria Groove", "photo": "/models/images/GloriaGroove.jpg"},
            {"name": "MC Kevinho", "photo": "/models/images/MCKevinho.jpg"},
            {"name": "MC Hariel", "photo": "/models/images/MCHariel.jpg"},
            {"name": "Felipe Araújo", "photo": "/models/images/FelipeAraujo.jpg"},
            {"name": "Wesley Safadão", "photo": "/models/images/WesleySafadao.jpg"},
            {"name": "Matheus & Kauan", "photo": "/models/images/MatheusAndKauan.jpg"},
            {"name": "Zé Neto & Cristiano", "photo": "/models/images/ZeNetoAndCristiano.jpg"},
            {"name": "Chico Buarque", "photo": "/models/images/ChicoBuarque.jpg"},
            {"name": "Caetano Veloso", "photo": "/models/images/CaetanoVeloso.jpg"},
            {"name": "Gilberto Gil", "photo": "/models/images/GilbertoGil.jpg"},
            {"name": "Maria Bethânia", "photo": "/models/images/MariaBethania.jpg"},
            {"name": "Elis Regina", "photo": "/models/images/ElisRegina.jpg"},
            {"name": "Roberto Carlos", "photo": "/models/images/RobertoCarlos.jpg"}
        ],
        "Russian": [
            {"name": "Zivert", "photo": "/models/images/Zivert.jpg"},
            {"name": "Artik & Asti", "photo": "/models/images/ArtikAndAsti.jpg"},
            {"name": "HammAli & Navai", "photo": "/models/images/HammAliAndNavai.jpg"},
            {"name": "Miyagi & Andy Panda", "photo": "/models/images/MiyagiAndAndyPanda.jpg"},
            {"name": "Macan", "photo": "/models/images/Macan.jpg"},
            {"name": "Ruki Vverh", "photo": "/models/images/RukiVverh.jpg"},
            {"name": "Klavdia Petrivna", "photo": "/models/images/KlavdiaPetrivna.jpg"},
            {"name": "Oxxxymiron", "photo": "/models/images/Oxxxymiron.jpg"},
            {"name": "Basta", "photo": "/models/images/Basta.jpg"},
            {"name": "Timati", "photo": "/models/images/Timati.jpg"},
            {"name": "Egor Kreed", "photo": "/models/images/EgorKreed.jpg"},
            {"name": "Jah Khalib", "photo": "/models/images/JahKhalib.jpg"},
            {"name": "Miyagi", "photo": "/models/images/Miyagi.jpg"},
            {"name": "Andy Panda", "photo": "/models/images/AndyPanda.jpg"},
            {"name": "Alla Pugacheva", "photo": "/models/images/AllaPugacheva.jpg"},
            {"name": "Valery Leontiev", "photo": "/models/images/ValeryLeontiev.jpg"},
            {"name": "Igor Krutoy", "photo": "/models/images/IgorKrutoy.jpg"},
            {"name": "Philip Kirkorov", "photo": "/models/images/PhilipKirkorov.jpg"},
            {"name": "Larisa Dolina", "photo": "/models/images/LarisaDolina.jpg"},
            {"name": "Sofia Rotaru", "photo": "/models/images/SofiaRotaru.jpg"}
        ],
        "Italian": [
            {"name": "Mahmood", "photo": "/models/images/Mahmood.jpg"},
            {"name": "Marco Mengoni", "photo": "/models/images/MarcoMengoni.jpg"},
            {"name": "Laura Pausini", "photo": "/models/images/LauraPausini.jpg"},
            {"name": "Eros Ramazzotti", "photo": "/models/images/ErosRamazzotti.jpg"},
            {"name": "Fedez", "photo": "/models/images/Fedez.jpg"},
            {"name": "Jovanotti", "photo": "/models/images/Jovanotti.jpg"},
            {"name": "Tiziano Ferro", "photo": "/models/images/TizianoFerro.jpg"},
            {"name": "Emma Marrone", "photo": "/models/images/EmmaMarrone.jpg"},
            {"name": "Alessandra Amoroso", "photo": "/models/images/AlessandraAmoroso.jpg"},
            {"name": "Mina", "photo": "/models/images/Mina.jpg"},
            {"name": "Giorgia", "photo": "/models/images/Giorgia.jpg"},
            {"name": "Elisa", "photo": "/models/images/Elisa.jpg"},
            {"name": "Annalisa", "photo": "/models/images/Annalisa.jpg"},
            {"name": "Ultimo", "photo": "/models/images/Ultimo.jpg"},
            {"name": "Luciano Pavarotti", "photo": "/models/images/LucianoPavarotti.jpg"},
            {"name": "Andrea Bocelli", "photo": "/models/images/AndreaBocelli.jpg"},
            {"name": "Domenico Modugno", "photo": "/models/images/DomenicoModugno.jpg"},
            {"name": "Mina", "photo": "/models/images/Mina.jpg"},
            {"name": "Adriano Celentano", "photo": "/models/images/AdrianoCelentano.jpg"},
            {"name": "Rita Pavone", "photo": "/models/images/RitaPavone.jpg"}
        ],
        "German": [
            {"name": "Rammstein", "photo": "/models/images/Rammstein.jpg"},
            {"name": "Robin Schulz", "photo": "/models/images/RobinSchulz.jpg"},
            {"name": "Capital Bra", "photo": "/models/images/CapitalBra.jpg"},
            {"name": "Apache 207", "photo": "/models/images/Apache207.jpg"},
            {"name": "Bausa", "photo": "/models/images/Bausa.jpg"},
            {"name": "Boney M.", "photo": "/models/images/BoneyM.jpg"},
            {"name": "Modern Talking", "photo": "/models/images/ModernTalking.jpg"},
            {"name": "Scorpions", "photo": "/models/images/Scorpions.jpg"},
            {"name": "Nena", "photo": "/models/images/Nena.jpg"},
            {"name": "Herbert Grönemeyer", "photo": "/models/images/HerbertGronemeyer.jpg"},
            {"name": "Udo Lindenberg", "photo": "/models/images/UdoLindenberg.jpg"},
            {"name": "Peter Maffay", "photo": "/models/images/PeterMaffay.jpg"},
            {"name": "Rea Garvey", "photo": "/models/images/ReaGarvey.jpg"},
            {"name": "Sarah Connor", "photo": "/models/images/SarahConnor.jpg"},
            {"name": "Rammstein", "photo": "/models/images/Rammstein.jpg"},
            {"name": "Scorpions", "photo": "/models/images/Scorpions.jpg"},
            {"name": "Modern Talking", "photo": "/models/images/ModernTalking.jpg"},
            {"name": "Boney M.", "photo": "/models/images/BoneyM.jpg"},
            {"name": "Nena", "photo": "/models/images/Nena.jpg"},
            {"name": "Herbert Grönemeyer", "photo": "/models/images/HerbertGronemeyer.jpg"}
        ],
        "Chinese": [
            {"name": "Jay Chou", "photo": "/models/images/JayChou.jpg"},
            {"name": "JJ Lin", "photo": "/models/images/JJLin.jpg"},
            {"name": "G.E.M.", "photo": "/models/images/GEM.jpg"},
            {"name": "Eason Chan", "photo": "/models/images/EasonChan.jpg"},
            {"name": "Hua Chenyu", "photo": "/models/images/HuaChenyu.jpg"},
            {"name": "Li Ronghao", "photo": "/models/images/LiRonghao.jpg"},
            {"name": "Wang Junkai", "photo": "/models/images/WangJunkai.jpg"},
            {"name": "Jackson Wang", "photo": "/models/images/JacksonWang.jpg"},
            {"name": "TFBOYS", "photo": "/models/images/TFBOYS.jpg"},
            {"name": "R1SE", "photo": "/models/images/R1SE.jpg"},
            {"name": "Zhou Shen", "photo": "/models/images/ZhouShen.jpg"},
            {"name": "Mao Buyi", "photo": "/models/images/MaoBuyi.jpg"},
            {"name": "Li Yuchun", "photo": "/models/images/LiYuchun.jpg"},
            {"name": "Zhang Bichen", "photo": "/models/images/ZhangBichen.jpg"},
            {"name": "Teresa Teng", "photo": "/models/images/TeresaTeng.jpg"},
            {"name": "Leslie Cheung", "photo": "/models/images/LeslieCheung.jpg"},
            {"name": "Anita Mui", "photo": "/models/images/AnitaMui.jpg"},
            {"name": "Jacky Cheung", "photo": "/models/images/JackyCheung.jpg"},
            {"name": "Faye Wong", "photo": "/models/images/FayeWong.jpg"},
            {"name": "Coco Lee", "photo": "/models/images/CocoLee.jpg"}
        ]
    }