import logging
from datetime import datetime
from typing import List, Dict, Optional

from fastapi import APIRouter, Request
from pydantic import BaseModel
from ..models.data import MusicData
from ..services.ml import analyze_mood_advanced, generate_playlist_ml
from ..utils.spotify import create_playlist, ensure_valid_token

logger = logging.getLogger("moodmuse.assessment")

router = APIRouter(prefix="/assessment", tags=["assessment"])

class LanguageSelection(BaseModel):
    languages: List[str]

class ArtistSelection(BaseModel):
    artists: List[str]

class AssessmentAnswers(BaseModel):
    languages: List[str]
    favorite_artists: List[str]
    mood: str

@router.get("/languages")
async def get_languages():
    data = MusicData()
    return {"languages": data.languages}

@router.get("/artists/{language}")
async def get_artists(language: str):
    data = MusicData()
    return {"artists": [a["name"] for a in data.artists.get(language, [])]}


def _extract_track_uri(track: dict) -> Optional[str]:
    """generate_playlist_ml's exact track shape isn't visible from this file,
    so this defensively supports the field names a Spotify-sourced track dict
    is most likely to use, rather than assuming one specific shape."""
    if not isinstance(track, dict):
        return None
    if track.get("uri"):
        return track["uri"]
    if track.get("id"):
        return f"spotify:track:{track['id']}"
    nested = track.get("track")  # some Spotify endpoints nest under "track"
    if isinstance(nested, dict):
        return _extract_track_uri(nested)
    return None


@router.post("/submit")
async def submit_assessment(
    request: Request,
    answers: AssessmentAnswers,
    mood_text: str = "",
    preference: str = "popular",
):
    ml_mood = analyze_mood_advanced(mood_text)
    playlist = generate_playlist_ml(
        answers.languages,
        answers.favorite_artists,
        mood_text
    )

    playlist_name = f"MoodMuse – {ml_mood['mood']} – {datetime.now().strftime('%b %d, %Y')}"
    spotify_link: Optional[str] = None

    # Only attempt real playlist creation if this browser session has
    # previously connected a Spotify account via /auth/spotify/login.
    # Any failure here — no session, expired/revoked token, Spotify API
    # error — falls through to spotify_link staying None. The recommended
    # tracks are still returned either way.
    token_info = ensure_valid_token(request.session.get("spotify_token"))
    if token_info:
        request.session["spotify_token"] = token_info  # persist any refresh
        track_uris = [uri for uri in (_extract_track_uri(t) for t in playlist) if uri]
        if track_uris:
            try:
                spotify_link = create_playlist(
                    access_token=token_info["access_token"],
                    name=playlist_name,
                    track_uris=track_uris,
                    public=True,
                    description=f"Generated by MoodMuse from your {ml_mood['mood']} mood check-in.",
                )
            except Exception as e:
                logger.warning("Playlist creation failed, returning tracks only: %s", e)
                spotify_link = None
        else:
            logger.info("No usable track URIs in generated playlist — skipping playlist creation.")
    else:
        logger.info("No connected Spotify session — skipping playlist creation.")

    return {
        "mood_analysis": ml_mood,
        "playlist": playlist,
        "spotify_link": spotify_link,
        "spotify_connected": bool(token_info),
        "message": "Advanced ML playlist ready!",
    }